=== Chicoryn/wowopt/character/character.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT character    (info,weights,additional_constraint*,items)>
<!ELEMENT info         (name?,realm?,region?,base)>
<!ATTLIST info         load (true|false) "false">
<!ELEMENT name         (#PCDATA)>
<!ELEMENT realm        (#PCDATA)>
<!ELEMENT region       (#PCDATA)>
<!ELEMENT base         ((strength|intellect|agility|stamina|resilience|hps|dps|spirit|haste|mastery|critical|hit|expertise|parry|mana|dodge|spell_penetration|spell_power|damage|attack_power|block|armor|ranged_attack_power)*)>
<!ELEMENT weights      ((strength|intellect|agility|stamina|resilience|hps|dps|spirit|haste|mastery|critical|hit|expertise|parry|mana|dodge|spell_penetration|spell_power|damage|attack_power|block|armor|ranged_attack_power)*)>
<!ELEMENT additional_constraint (#PCDATA)>
<!ATTLIST additional_constraint file CDATA #IMPLIED>
<!ELEMENT items        (item*)>
<!ELEMENT item         (#PCDATA)>

<!ELEMENT strength (#PCDATA)>
<!ELEMENT intellect (#PCDATA)>
<!ELEMENT agility (#PCDATA)>
<!ELEMENT stamina (#PCDATA)>
<!ELEMENT resilience (#PCDATA)>
<!ELEMENT hps (#PCDATA)>
<!ELEMENT dps (#PCDATA)>
<!ELEMENT spirit (#PCDATA)>
<!ELEMENT haste (#PCDATA)>
<!ELEMENT mastery (#PCDATA)>
<!ELEMENT critical (#PCDATA)>
<!ELEMENT hit (#PCDATA)>
<!ELEMENT expertise (#PCDATA)>
<!ELEMENT parry (#PCDATA)>
<!ELEMENT mana (#PCDATA)>
<!ELEMENT dodge (#PCDATA)>
<!ELEMENT spell_penetration (#PCDATA)>
<!ELEMENT spell_power (#PCDATA)>
<!ELEMENT damage (#PCDATA)>
<!ELEMENT attack_power (#PCDATA)>
<!ELEMENT block (#PCDATA)>
<!ELEMENT armor (#PCDATA)>
<!ELEMENT ranged_attack_power (#PCDATA)>

=== Chicoryn/wowopt/character/Ecdab@eu-Alonsus.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <!-- Character information. If load is set to true then all currently
       equipped items will be added to the model.
    -->
  <info load="true">
    <name>Ecdab</name> <!-- Ignored unless load = true -->
    <realm>Alonsus</realm> <!-- Ignored unless load = true -->
    <region>eu</region> <!-- Ignored unless load = true -->

    <!-- Character base stats at level 85 -->
    <base>
      <intellect>39</intellect>
      <stamina>203</stamina>
      <strength>186</strength>
      <agility>123</agility>
      <spirit>63</spirit>
    </base>
  </info>

  <!-- The weights of each stat in the objective function, to be
       maximised, in the solver. Terms in the objective function
       are:
           * strength
           * intellect
           * agility
           * stamina
           * resilience
           * hps
           * dps
           * spirit
           * haste
           * mastery
           * critical
           * hit
           * expertise
           * parry
           * mana
           * dodge
           * spell_penetration
           * spell_power
           * damage
           * attack_power
           * ranged_attack_power
           * block
           * armor
       If one or more attributes are omitted they default to zero.
    -->
  <weights>
    <strength>0.284</strength>
    <stamina>0.65</stamina>
    <armor>0.153</armor>
    <parry>1</parry>
    <dodge>1</dodge>
    <mastery>0.8</mastery>
    <expertise>0.4</expertise>
    <hit>0.2</hit>
  </weights>

  <!-- Any additional constraints that one might want to add
       to the model. A constraint is written in Python with
       *full* access to all internal states of the solver.

       Note that you need to follow all standard coding
       conventions, such as line indention, when writing
       the Python code. The only help the solver provides is
       that is strip all whitespace from the end of your
       constraint.
    -->
  <additional_constraint file="constraints/meta_2x_yellow.py" />
  <additional_constraint file="constraints/bonus_4percent_parry.py" />
  <additional_constraint file="constraints/bonus_27percent_str_parry.py" />
  <additional_constraint>
<![CDATA[
problem += self.penalty >= 1 * self.total_stats[I['parry']] - 1 * self.total_stats[I['dodge']]
problem += self.penalty >= 1 * self.total_stats[I['dodge']] - 1 * self.total_stats[I['parry']]
]]>
  </additional_constraint>
  <additional_constraint file="constraints/bonus_procs.py" />

  <!-- Any items (by ID) one wish to add to the model. -->
  <items>
  </items>
</character>

=== Chicoryn/wowopt/character/Kiaclei@eu-Alonsus.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <!-- Character information. If load is set to true then all currently
       equipped items will be added to the model.
    -->
  <info load="true">
    <name>Kiaclei</name> <!-- Ignored unless load = true -->
    <realm>Alonsus</realm> <!-- Ignored unless load = true -->
    <region>eu</region> <!-- Ignored unless load = true -->

    <!-- Character base stats at level 85 -->
    <base>
      <intellect>169</intellect>
      <stamina>106</stamina>
      <strength>99</strength>
      <agility>91</agility>
      <spirit>172</spirit>
    </base>
  </info>

  <!-- The weights of each stat in the objective function, to be
       maximised, in the solver. Terms in the objective function
       are:
           * strength
           * intellect
           * agility
           * stamina
           * resilience
           * hps
           * dps
           * spirit
           * haste
           * mastery
           * critical
           * hit
           * expertise
           * parry
           * mana
           * dodge
           * spell_penetration
           * spell_power
           * damage
           * attack_power
           * ranged_attack_power
           * block
           * armor
       If one or more attributes are omitted they default to zero.
    -->
  <weights>
    <intellect>3.32</intellect>
    <spell_power>2.43</spell_power>
    <critical>0.89</critical>
    <haste>1.92</haste>
    <mastery>1.27</mastery>
  </weights>

  <!-- Any additional constraints that one might want to add
       to the model. A constraint is written in Python with
       *full* access to all internal states of the solver.

       Note that you need to follow all standard coding
       conventions, such as line indention, when writing
       the Python code. The only help the solver provides is
       that is strip all whitespace from the end of your
       constraint.
    -->
  <additional_constraint file="constraints/meta_3x_red.py" />
  <additional_constraint file="constraints/bonus_100percent_spirit_hit.py" />
  <additional_constraint>
<![CDATA[
problem += self.total_stats[I['hit']] >= 1742
]]>
</additional_constraint>

  <!-- Any items (by ID) one wish to add to the model. -->
  <items>
  </items>
</character>

=== Chicoryn/wowopt/character/Cherdin@eu-Alonsus.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <!-- Character information. If load is set to true then all currently
       equipped items will be added to the model.
    -->
  <info load="true">
    <name>Cherdin</name> <!-- Ignored unless load = true -->
    <realm>Alonsus</realm> <!-- Ignored unless load = true -->
    <region>eu</region> <!-- Ignored unless load = true -->

    <!-- Character base stats at level 85 -->
    <base>
      <intellect>199</intellect>
      <stamina>71</stamina>
      <strength>46</strength>
      <agility>54</agility>
      <spirit>197</spirit>
    </base>
  </info>

  <!-- The weights of each stat in the objective function, to be
       maximised, in the solver. Terms in the objective function
       are:
           * strength
           * intellect
           * agility
           * stamina
           * resilience
           * hps
           * dps
           * spirit
           * haste
           * mastery
           * critical
           * hit
           * expertise
           * parry
           * mana
           * dodge
           * spell_penetration
           * spell_power
           * damage
           * attack_power
           * ranged_attack_power
           * block
           * armor
       If one or more attributes are omitted they default to zero.
    -->
  <weights>
    <intellect>2.8820</intellect> <!-- 3.48 / (1.15 * 1.05) -->
    <spirit>2.0971</spirit> <!-- 2.16 / 1.03 -->
    <haste>0</haste>
    <mastery>1.81</mastery>
    <critical>1.61</critical>
    <spell_power>1.76</spell_power>
    <hps>1</hps>
  </weights>

  <!-- Any additional constraints that one might want to add
       to the model. A constraint is written in Python with
       *full* access to all internal states of the solver.

       Note that you need to follow all standard coding
       conventions, such as line indention, when writing
       the Python code. The only help the solver provides is
       that is strip all whitespace from the end of your
       constraint.
    -->
  <additional_constraint file="constraints/meta_54_int.py" />
  <additional_constraint file="constraints/meta_2x_yellow.py" />
  <additional_constraint file="constraints/t11_set_bonus_disc.py" />
  <additional_constraint file="constraints/t12_set_bonus.py" />
  <additional_constraint file="constraints/prof_61_int.py" />
  <additional_constraint file="constraints/bonus_5percent_int.py" />
  <additional_constraint file="constraints/bonus_15percent_int.py" />
  <additional_constraint file="constraints/bonus_3percent_spirit.py" />
  <additional_constraint>
<![CDATA[
problem += self.total_stats[I['haste']] >= 517 # 3/3 darkness
# problem += self.total_stats[I['haste']] >= 646 # 2/3 darkness
# problem += self.total_stats[I['haste']] >= 780 # 1/3 darkness
# problem += self.total_stats[I['haste']] >= 915 # 0/3 darkness
]]>
  </additional_constraint>
  <additional_constraint>
<![CDATA[
choice_items = [ ]
choice_items = [ self.used[item] for item in self.get_items() if item.item_id in choice_items ]

if choice_items:
    problem += pulp.lpSum(choice_items) <= 1
]]>
  </additional_constraint>

  <!-- Any items (by ID) one wish to add to the model. -->
  <items>
  </items>
</character>

=== Chicoryn/wowopt/character/Rnyi@eu-Alonsus.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE character SYSTEM "character.dtd">
<character>
  <!-- Character information. If load is set to true then all currently
       equipped items will be added to the model.
    -->
  <info load="true">
    <name>Rnyi</name> <!-- Ignored unless load = true -->
    <realm>Alonsus</realm> <!-- Ignored unless load = true -->
    <region>eu</region> <!-- Ignored unless load = true -->

    <!-- Character base stats at level 85 -->
    <base>
      <strength>117</strength>
      <agility>218</agility>
      <stamina>114</stamina>
      <intellect>49</intellect>
      <spirit>71</spirit>
    </base>
  </info>

  <!-- The weights of each stat in the objective function, to be
       maximised, in the solver. Terms in the objective function
       are:
           * strength
           * intellect
           * agility
           * stamina
           * resilience
           * hps
           * dps
           * spirit
           * haste
           * mastery
           * critical
           * hit
           * expertise
           * parry
           * mana
           * dodge
           * spell_penetration
           * spell_power
           * damage
           * attack_power
           * ranged_attack_power
           * block
           * armor
       If one or more attributes are omitted they default to zero.
    -->
  <weights>
    <agility>2.7</agility>
    <attack_power>1.0</attack_power>
    <hit>1.4</hit>
    <expertise>1.65</expertise>
    <mastery>1.2</mastery>
    <haste>1.5</haste>
    <critical>0.9</critical>
  </weights>

  <!-- Any additional constraints that one might want to add
       to the model. A constraint is written in Python with
       *full* access to all internal states of the solver.

       Note that you need to follow all standard coding
       conventions, such as line indention, when writing
       the Python code. The only help the solver provides is
       that is strip all whitespace from the end of your
       constraint.
    -->
  <additional_constraint file="constraints/meta_3x_red.py" />
  <additional_constraint>
<![CDATA[
problem += self.total_stats[I['hit']] >= 241  # Yellow Hit
problem += self.total_stats[I['hit']] <= 1128 # Spell Hit
]]>
  </additional_constraint>
  <additional_constraint>
<![CDATA[
# Expertise cap, note that it's enough to cap only one of your weapons before
# the weights drops significantly. In this model it drops to zero, which is
# inaccurate but produce the desired result.
expertise_cap = 691 # 781 if no racial
expertise_pen = pulp.LpVariable('expertise_penalty', 0, cat = 'Integer')

problem += expertise_pen >= self.total_stats[I['expertise']] - expertise_cap
problem += self.penalty == self.weight[I['expertise']] * expertise_pen
]]>
  </additional_constraint>
  <additional_constraint file="constraints/bonus_procs.py" />

  <!-- Any items (by ID) one wish to add to the model. -->
  <items>
  </items>
</character>
